export { default as TestPage } from './TestPage';
export { default as CountPage } from './CountPage';
export { default as Page } from './Page';
export { default as SignUpPage } from './SignUpPage';
export { default as AuthPage } from './AuthPage';
export { default as MyPageEdit } from './MyPageEdit';
export { default as MyPageLike } from './MyPageLike';
export { default as MyPageReport } from './MyPageReport';
export { default as PublicPage } from './PublicPage';
